# Lista \#1

## Isabella B. --- 11810773

---

1.
    a. Denotando Cara por $H$ e Coroa por $T$, temos que:

        $$S=\left\lbrace 1HH,1HT,1TH,1TT, 2HH,2HT,2TH,2TT, 3HH,3HT,3TH,3TT,\right.$$
        $$\hspace{2.1em}\left.4HH,4HT,4TH,4TT, 5HH,5HT,5TH,5TT, 6HH,6HT,6TH,6TT \right\rbrace$$

    b. Para o primeiro caso: $3/24 = 1/8$
        
        Para o segundo caso: $6/24 = 1/3$

        Para o terceiro caso: $12/24 = 1/2$

2. Para a situação de 4 portas, onde o apresentador só abre uma, temos que a
    chance da porta selecionada ser a correta é de $1/4$, e como a porta aberta
    tem chance nula de ser correta, as outras terão $3/8$ de chance de serem a
    porta correta.

    Na simulação conseguimos $\approx0.375$, o que é a resposta esperada.
