# Exercício \#1

## Isabella B. --- 11810773

---

1. Faça uma análise termodinâmica qualitativa da dissolução de hexanol em água;
faça o mesmo para dodecilssulfato de sódio em água

Para o caso do hexanol, notamos que sua hidroxila permite interações fortes
(i.e. ligações de hidrogênio) com a água, de tal forma que, entropicamente, a
dissolução "caótica" é bastante favorável, já que forma um sistema mais
desordenado do que quando as substâncias estão separadas. Pela equação da
energia livre de Gibbs, considerando que não há reações unidirecionais
($\implies \Delta H\approx0$) e a entropia aumenta por conta das ligações de
hidrogênio, temos

$$\Delta G=\Delta H-T\Delta S\approx 0 - T\Delta S \ll 0$$

De tal forma que a solubilização é imediata.

Avaliando, agora, o caso do dodecilssulfato de sódio, temos que este é um
composto anfifílico (por conta de sua "cabeça" polar seguida de uma estrutura
rica em carbonos) e, daí, sabemos que formam-se as chamadas "micelas",
novamente por conta do aumento de entropia: Como a introdução desse composto na
água iria agir parcialmente em detrimento das reações entre moléculas de água
adjacentes (já que o corpo apolar do dodecilssulfato atrapalha estas), temos,
então, que esse composto tende a se organizar de formar a formar "amontoados",
criando novas interfaces com a água (como superfícies internas) e, sendo uma
parte polar, esta tende a ter contato com a água, enquanto a outra deve
interagir somente com outras móleculas idênticas. Novamente, a avaliação da
energia livre nos deve dar algo como acima, onde $\Delta G \ll 0$ para o caso
especificado.
