# Exercício \#10

## Isabella B. --- 11810773

---

a. Essa é a energia adquirida pelo sistema na troca de elétrons em relação à
    reorganização simples dos núcleos.

b. A velocidade é máxima quando $\Delta G$ e $\lambda$ são minimizados, dado
   que $k$ é função de uma exponencial decrescente:

   $$k=A e^{-\frac{(\Delta G+\lambda)^2}{4\lambda RT}},$$
   o que se justifica, dado que, numa reação onde os produtos são similares
   aos reagentes (i.e. $\lambda$ pequeno) e com baixa energia de ativação,
   eles possuem velocidades relativamente maiores por natureza.

c. Pela teoria de Marcus temos que:

   ![Marcus graphic](20211022_185722.jpg)

   Sendo $\Delta E_A=(\Delta G + \lambda)^2/(4\lambda)$, temos que a energia
   de ativação é proporcional ao quadrado de $\Delta G$, e como esta
   influencia diretamente a velocidade uma reação, sendo a taxa de velocidade
   $$k=A e^{-\frac{(\Delta G+\lambda)^2}{4\lambda RT}}=Ae^{-\Delta E_A/(RT)}$$
   é fácil notal que, à medida que $\Delta G$ de uma reação diminui, sua
   velocidade aumenta.

d. O aumento de distância dos centros atômicos influencia uma parte da equação,
   apenas.

   Sendo
   $$k=c e^{-\beta n}\alpha,$$
   onde $\alpha = e^{-\Delta E_A/(RT)}$ será considerado constante, sem perda
   de generalidade. Sendo então $k_i$ o valor inicial e $k_f$ o final, temos
   $$19k_i = k_f \implies 10ce^{-\beta n} = ce^{-\beta n}\implies \ln 10 - \beta r_i = \beta(r_i + 5)$$
   $$\implies \beta = -\frac{\ln 10}{5}$$

e. Dado
   $$k=A e^{-\frac{(\Delta G+\lambda)^2}{4\lambda RT}},$$
   temos que
   $$k=2k_0$$
   o que implica em
   $$A e^{-\frac{(\Delta G+\lambda)^2}{4\lambda R(T+37)}}=2A e^{-\frac{(\Delta G+\lambda)^2}{4\lambda RT}}$$
   $$\implies \frac{-(\Delta G+\lambda)^2}{4\lambda R(T+37)}=\ln 2-\frac{(\Delta G+\lambda)^2}{4\lambda RT}$$
   $$\implies \frac{(\Delta G+\lambda)^2}{4\lambda R}\left(-\frac{1}{(T+37)}+\frac{1}{T}\right)=\ln 2$$
   $$\implies \frac{(\Delta G+\lambda)^2}{4\lambda R}\left(\frac{37}{T(T+37)}\right)=\ln 2$$
   $$\implies \frac{(\Delta G+\lambda)^2}{\lambda}=\underbrace{\frac{4RT(T+37)\ln 2}{37}}_{\psi}$$
   Por Bhaskara, temos
   $$\lambda = \frac{1}{2}(\pm\sqrt{\psi^2-4\Delta G \psi}-2\Delta G +\psi)$$
