# Exercício \#11

## Isabella B. --- 11810773

---

1. Do primeiro artigo, conseguimos notar que em 1927 o peso atômico fora
    determinado com um espectrometro de massas, confirmando o valor
    experimental aceito na química. Então, em 1929 descobriu-se que havia uma
    distribuição de oxigênio com outros isótopos, o que indicava a existência
    de um isótopo do hidrogênio.

    Em 1932, Urey, Brickwedde e Murphy tinham encontrado evidências que
    indicavam a existência desse isótopo (um hidrogênio pesado) em uma pequena
    amostra de hidrogênio concentrado por meio de destilação.

    Ainda nesse ano, Washburn e Urey realizaram o enriquecimento do hidrogênio
    em água por meio de eletrólise, e outra dupla de cientistas conseguiram
    isolar uma pequena amostra de água pesada.

    Devido à alta disponibilidade do isótopo deutério, sua aplicação em
    diversos estudos foi rápida, e em 1934 já haviam diversos artigos à
    respeito disso.

    Quando confirmado que o deutério de fato existia, também previu-se que este
    deveria reagir a uma taxa diferente daquela do hidrogênio, o que foi,
    então, verificado, e levou esse isótopo a ser bastante valorizado em
    experimentos por conta dessa propriedade.

2.

3. Na figura do artigo, vemos o gráfico mostrando uma superfície que indica a
    energia potencial da reação estudada. Verifica-se, a partir desta, que os
    caminhos dinâmicos típicos convergem para o primeiro produto (em sua
    maioria), de tal forma que esse produto é mais abundante. Essa seletividade
    é uma forma de efeito isotópico, e não se relaciona com o efeito usual das
    energias do ponto zero nas barreiras.

    De acordo com o artigo, esse efeito ocorre por conta da assimetricidade
    inerente aos modos vibracionais dos compostos marcados isotopicamente.
    Devido à serem não-harmônicos, o comprimento médio de sua ligações
    carbono-hidrogênio é maior que das ligações entre o carbono e outros
    compostos. Dessa forma, uma perturbação assimétrica mínima pode levar as
    trajetórias em torno do VRI para a formação preferencial de um produto.

4. No artigo os autores resolvem o problema por meio de efeitos isotópicos.
    Isso se dá graças à substituição do composto O-metila crítico por um grupo
    O-trideuteriometil. Em seu experimento, os autores precisarem somente
    utilizar um reagente de metialação deuterado ao invés de um sulfato de
    dimetilo previamente adotado e, como usualmente o grupo sililo seria
    removido e o naftol metilado com o sulfato de dimetilo, agora fez-se
    necessário tratar o naftol com o d3 p-toluenossulfonatel e hidreto de
    sódio. Após estas trocas, o experimento continua como planejado e, por fim,
    o grupo fenilseleno fora introduzido por meio do éter sililenólico.

    Ao ser tratado nas condições padrão (utilizando benzeno de refluxo) com
    hidreto de uifenilestanho e AIBN, o seleneto deuterado formou compostos
    espirocíclicos com alto rendimento e quase nenhum material indesejado. A
    proporção 31:32 (quase 1:1) torna-se agora 9:7:1, o que é uma melhora
    significativa em relação à série não deuterada, o que não é propriamente
    explicado no artigo, infelizmente.

