# Exercício \#4

## Isabella B. --- 11810773

---

1. Faça o diagrama LCAO-MO para LiF. Como explicar a ligação iônica no LiF.

    O diagrama abaixo parece uma depicção correta da situação.
    ![](20210909_110754.jpg)
    De tal forma que podemos notar que as camadas de valência dos compostos se
    complementam, e então quando se ligam existe uma disposição eletrônica em
    que os orbitais ligantes ficam preenchidos (nesse caso somente um) e os
    orbitais anti-ligantes vazios. Creio que esse fenômeno provoca ligações mais intensas do que as moleculares normais, tendo uma distância significativamente menor do que as outras.

2. Faça o diagrama LCAO-MO para NO deduza as principais propriedades baseado
nele.

    Sendo o diagrama razoável
    ![](20210909_113716.jpg)
    podemos notar que existe um elétron com spin desemparelhado em um orbital
    anti-ligante de alta energia, de tal forma que essa molécula constitui um
    radical livre, além de ser altamente reativa, e por ter algum orbital
    anti-ligante preenchido, definitivamente não devem fazer ligação iônica.

Referências
--
[Molecular Orbital Theory. (2015, October 3). Retrieved September 9, 2021](https://chem.libretexts.org/@go/page/37046)
