# Exercício \#5

## Isabella B. --- 11810773

---

1. Suponha que você tenha $n$ moles de RH e $n$ moles de X$_2$ e apenas 1 átomo
de X radicular. Considerando que estão em fase gasosa, que cada encontro pode
gerar um produto, que só o H é reativo no RH, como calcular o número provável
de ciclos gerados pelo átomo X?

    Possuindo as constantes de equilíbrio das reações intermediárias (parâmetro
    experimental), podemos usá-las como probabilidades para tais reações, de
    tal forma que é possível aplicar o cálculo da esperança do número de ciclos
    gerados pelo átomo X. A esperança nos dá o número esperado para um evento
    pela soma das probabilidades onde o evento ocorre ponderadas pelo resultado
    à que correspondem, i.e.:

    $$\mathbb{E}[\text{ciclos gerados por X}]=\sum^\infty_{k=0} k\cdot\mathbb{P}(k\text{ ciclos})$$

2. Faça um resumo das conclusões do paper anexado sobre porque uma espécie
biradicalar tão reativa é tão "cinéticamente persistente".

    Sendo as reações de abstração de H mais endotérmicas do que àquelas opostas
    --- o que leva o O$_2$ a persistir já que a abstração de H pelo OOH$^-$ é
    entalpicamente mais favorável ---, temos também que a trimerização de O$_2$
    é bastante endotérmica, o que também faz o O$_2$ ser persistente. Por trás
    desses fenômenos temos as ligações que compõem a molécula, e que possuem
    grande energia de ressonância devido à uma forte ligação $\pi$ (mais forte
    que sua ligação $\sigma$) e que libera muita energia quando quebrada. Isso
    torna o O$_2$ uma molécula persistente e também faz com que ela seja capaz
    de prover energia para os seres vivos aeróbicos no nosso planeta.
