# Exercício \#7

## Isabella B. --- 11810773

---

1. Faça uma análise da origem das estabilidades conformacionais do etano
baseado nos artigos:
   1. Weinhold, "A new twist on molecular shape"
   2. Alabugin, "Hyperconjugation"

    De acordo com Kemp & Pitzer (1936), o perfil energético interno da
    estrutura do etano foi esboçado com base no seu ângulo de rotação diedral.
    Nessa exploração eles mostraram que existem três pontos de energia mínima,
    que correspondem à conformação _staggered_, e são intercalados por pontos
    de máximo, os quais correspondem à conformação _eclipsed_, formando
    barreiras energéticas que impedem rotações. Normalmente, atribui-se esse
    fenômeno à repulsão estérica entre orbitais ocupados, os quais se opõem à
    sua sobreposição (que seria minimizada na conformação alternada).
    Porém, utilizando métodos computacionais, Pophristic & Goodman (2001)
    conseguiram avaliar as interações entre os orbitais do etano, revelando que
    suas repulsões estéricas, na verdade, não são o fator determinante para a
    estabilidade conformacional, e que favorecem sua conformação eclipsada.

    Dessa forma, nos artigos avaliados, podemos notar que as interações
    quânticas entre os orbitais do etano são, de fato, as principais
    responsáveis  pela sua conformação dominante ser alternada. Existe uma
    interação de hiperconjugação (i.e. interação entre orbitais $\sigma$) na
    qual ocorre uma transferência parcial de elétrons de um orbital ligante
    quase duplamente ocupado para um antiligante quase vazio. A mistura dos
    orbitais $\sigma_{\text{CH}}$--$\sigma^\star_{\text{CH}}$ na conformação
    alternada é mais favorável do que na outra, por conta da aproximação dos
    seus orbitais, que torna a interação mais estabilizante. Na conformação
    eclipsada há uma sobreposição energeticamente desfavorável dos orbitais
    (i.e. um mínimo local de energia), como ilustrado na figura abaixo,
    retirada de Weinhold (2001).

    ![](2021-10-02-15-59-09.png)

    Na conformação alternada, então, existe uma interação forte de
    hiperconjugação entre os orbitais, que provoca uma redução energética
    significativa, ao ponto que leva à deslocalização eletrônica, onde os
    elétrons de um orbital ocupado podem se mover parcialmente para o orbital
    desocupado. A força dessas deslocalizações é um fator determinante para a
    estabilidade de uma conformação sobre a outra.

    A deslocalização de elétrons em orbitais ligantes também pode levar a
    padrões de ligação alternativos, conhecidos como estruturas de ressonância,
    de tal forma que as barreiras energéticas do etano podem ser compreendidas
    como artefatos de hiperconjugação que levam à estabilização das estruturas
    de ressonância do etano para os elétrons que realizam ligações $\sigma$,
    mais fracas, no entanto relacionadas com a estabilização de ressonância dos
    elétrons $\pi$ em sistemas que possuem ligações simples e duplas
    alternantes. Nessa ótica, o etano busca simplesmente uma estabilização de
    ressonância ótima.
